steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$_PROJECT_ID/dotnet-app:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$_PROJECT_ID/dotnet-app:latest'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instances'
      - 'create-with-container'
      - 'my-instance'
      - '--container-image'
      - 'gcr.io/$_PROJECT_ID/dotnet-app:latest'
      - '--zone'
      - 'us-central1-a'

timeout: 1200s
