name: .NET with Docker and Google Cloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for Google Cloud
      run: |
        gcloud auth configure-docker gcr.io --quiet

    - name: Build Docker image
      run: |
        echo "Building the Docker image..."
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/device-management-api:latest .

    - name: Push Docker image to Google Container Registry
      run: |
        echo "Pushing the Docker image to Google Container Registry..."
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/device-management-api:latest

    - name: Deploy to Google Cloud Run
      run: |
        echo "Deploying the Docker container to Google Cloud Run..."
        gcloud run deploy device-management-api \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/device-management-api:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
