name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Application
      run: |
        dotnet run --project ./DeviceManagementApi/DeviceManagementApi.csproj
      env:
        ConnectionStrings__DefaultConnection: ${{ secrets.DATABASE_CONNECTION_STRING }}

    - name: Run tests and generate code coverage
      run: dotnet test --collect:"XPlat Code Coverage" --no-build --verbosity normal
