name: .NET with Docker and Google Cloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure gcloud
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set compute/region ${{ secrets.GCP_REGION }}

    - name: Run Cloud Build
      run: |
        gcloud builds submit \
            --substitutions _PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} \
            --config cloudbuild.yaml .

    - name: Deploy to Google Cloud Run
      run: |
        echo "Deploying the Docker container to Google Cloud Run..."
        gcloud run deploy device-management-api \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/device-management-api:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
